default:
  # https://gitlab.com/mtczekajlo/lsm6ds3tr-rs-docker
  image: registry.gitlab.com/mtczekajlo/lsm6ds3tr-rs-docker:2a8ade0b2c3550489dc50e912fb8c0de

stages:
  - check
  - build
  - test

check:
  stage: check
  dependencies: []
  script:
    - ci/jobs/check

doc:
  stage: check
  dependencies: []
  script:
    - ci/jobs/doc
  allow_failure: true

build:
  stage: build
  needs: ["check"]
  dependencies: ["check"]
  script:
    - ci/jobs/build

test:
  stage: test
  needs: ["build"]
  dependencies: ["build"]
  script:
    - ci/jobs/test
