default:
  # https://gitlab.com/mtczekajlo/lsm6ds3tr-rs-docker
  image: registry.gitlab.com/mtczekajlo/lsm6ds3tr-rs-docker:f3598e64faee1b7e66b2bb792fce3290

stages:
  - check
  - build
  - test

check:
  stage: check
  dependencies: []
  script:
    - ci/jobs/check

doc:
  stage: check
  dependencies: []
  script:
    - ci/jobs/doc

build:
  stage: build
  needs: ["check"]
  dependencies: ["check"]
  script:
    - ci/jobs/build

test:
  stage: test
  needs: ["build"]
  dependencies: ["build"]
  script:
    - ci/jobs/test
