default:
  # https://gitlab.com/mtczekajlo/lsm6ds3tr-rs-docker
  image: registry.gitlab.com/mtczekajlo/lsm6ds3tr-rs-docker:9d1f2e8b31e941493aa16a5f46802af7

stages:
  - check
  - build
  - test

check:
  stage: check
  dependencies: []
  script:
    - ci/jobs/check

doc:
  stage: check
  dependencies: []
  script:
    - ci/jobs/doc

build:
  stage: build
  needs: ["check"]
  dependencies: ["check"]
  script:
    - ci/jobs/build

test:
  stage: test
  needs: ["build"]
  dependencies: ["build"]
  script:
    - ci/jobs/test
