#!/usr/bin/env bash
set -xEeuo pipefail

cd "$(git rev-parse --show-toplevel)"

ci/format
ci/check
ci/check --features defmt
ci/check --release
ci/check --features defmt --release
ci/clippy
ci/clippy --release
ci/cargo-sort
ci/udeps
ci/udeps --release
