#![allow(unused_imports)]

pub mod addresses;
pub mod ctrl1_xl;
pub mod ctrl2_g;
pub mod ctrl3_c;
pub mod ctrl4_c;
pub mod drdy_pulse_cfg_g;
pub mod free_fall;
pub mod int1_ctrl;
pub mod int2_ctrl;
pub mod int_dur2;
pub mod md1_cfg;
pub mod md2_cfg;
pub mod tap_cfg;
pub mod tap_src;
pub mod tap_ths_6d;
pub mod wake_up_dur;
pub mod wake_up_src;
pub mod wake_up_ths;

pub use addresses::*;
pub use ctrl1_xl::*;
pub use ctrl2_g::*;
pub use ctrl3_c::*;
pub use ctrl4_c::*;
pub use drdy_pulse_cfg_g::*;
pub use free_fall::*;
pub use int1_ctrl::*;
pub use int2_ctrl::*;
pub use int_dur2::*;
pub use md1_cfg::*;
pub use md2_cfg::*;
pub use tap_cfg::*;
pub use tap_src::*;
pub use tap_ths_6d::*;
pub use wake_up_dur::*;
pub use wake_up_src::*;
pub use wake_up_ths::*;
